const assert=require('node:assert/strict');
let L={};try{L=require('../web/ledger.js')}catch(e){if(e.code!=='MODULE_NOT_FOUND')throw e}
assert.equal(typeof L.summary,'function','ledger summary must exist');
const base={id:'a',suggested:'2026-09-30',order:null,items:[{name:'牙膏A',category:'牙膏',quantity:2,unit:'支'}],amount:65,purchaseDate:'2026-09-20',actualService:'2026-09-25',bookingDate:'2026-09-25'};
const pending={...base,id:'b',amount:99,purchaseDate:'',actualService:'',bookingDate:''};
const bought={...base,id:'c',amount:70,purchaseDate:'2026-09-26',actualService:'',bookingDate:''};
const missing={...base,id:'d',amount:null,purchaseDate:'',actualService:'2026-09-26'};
let s=L.summary([base,pending,bought,missing]);assert.equal(s.spent,135);assert.equal(s.completed,2);assert.equal(s.average,65);assert.equal(s.missingCost,1);assert.equal(s.groups[0].purchases,2);assert.equal(s.groups[0].name,'牙膏A');
assert.equal(L.duplicates(pending,[base,pending,bought],'2026-10-10').length,1);assert.equal(L.duplicates(pending,[base],'2026-10-21').length,0);
assert.equal(L.summary([]).average,null);
assert.throws(()=>L.validateState({version:2,plans:'bad'}));
const state={version:2,config:{},activeId:'p',plans:[{id:'p',start:'2026-09-30',config:{},rows:[base]}]};assert.deepEqual(L.validateState(JSON.parse(JSON.stringify(state))),state);
assert.throws(()=>L.validateState({...state,plans:[{...state.plans[0],rows:[{...base,amount:-3}]}]}));
assert.throws(()=>L.validateState({...state,plans:[{...state.plans[0],rows:[{...base,items:[{name:'x',category:'牙膏',quantity:-1,unit:'支'}]}]}]}));
assert.equal(L.summary([{...base,amount:0.1},{...base,id:'z',amount:0.2}]).spent,0.3);
assert.equal(L.bookingWarnings([{...base,bookingDate:'2026-09-01'},{...base,id:'b',bookingDate:'2026-09-10'},{...base,id:'c',bookingDate:'2026-09-20'},{...base,id:'d',bookingDate:'2026-09-30'}],1).length,1);
console.log('Ledger checks passed');
assert.equal(typeof L.purchase,'function','purchase must capture visible form values');
const draft={...base,items:[{name:'',category:'牙膏',quantity:1,unit:'支'}],amount:null,purchaseDate:''};
const recorded=L.purchase(draft,{date:'2026-09-20',amount:'65',items:[{name:'测试牙膏',category:'牙膏',quantity:'2',unit:'支'}]},'2026-09-27');
assert.equal(recorded.items[0].name,'测试牙膏');assert.equal(recorded.items[0].quantity,2);assert.equal(recorded.amount,65);assert.equal(draft.purchaseDate,'');
assert.throws(()=>L.purchase(draft,{date:'2026-09-20',amount:'',items:recorded.items},'2026-09-27'));
assert.throws(()=>L.validateState({...state,config:{price:'invalid'}}),'reject malformed configuration');
const upgraded=L.upgradeState(structuredClone(state));
assert.equal(upgraded.version,3);
assert.equal(upgraded.activeAccount,'1');
assert.equal(upgraded.plans[0].accountId,'1');
assert.deepEqual(upgraded.plans[0].rows,state.plans[0].rows);
assert.deepEqual(upgraded.accounts['2'],{config:{},activeId:''});
assert.equal(state.version,2,'migration must not mutate its input');
assert.deepEqual(L.validateState(upgraded),upgraded);
assert.deepEqual(L.upgradeState(structuredClone(upgraded)),upgraded,'migration is idempotent');
const brokenAccount=structuredClone(upgraded);brokenAccount.plans[0].accountId='3';
assert.throws(()=>L.validateState(brokenAccount));
const wrongSelection=structuredClone(upgraded);wrongSelection.accounts['2'].activeId='p';
assert.throws(()=>L.validateState(wrongSelection),'selection cannot point at another account');
assert.throws(()=>L.validateState({...upgraded,activeAccount:'3'}));
const invalidAccountConfig=structuredClone(upgraded);invalidAccountConfig.accounts['2'].config={price:'invalid'};
assert.throws(()=>L.validateState(invalidAccountConfig));
console.log('Account migration and validation checks passed');
const namesOnly=L.purchase(base,{date:'2026-09-20',amount:'65',items:[{name:'  牙膏A  '}]},'2026-09-27');
assert.deepEqual(namesOnly.items,base.items,'name-only edits retain legacy metadata');
const newName=L.purchase({...draft,items:[]},{date:'2026-09-20',amount:'10',items:[{name:'纸巾'}]},'2026-09-27');
assert.equal(newName.items[0].name,'纸巾');
assert.equal(newName.items[0].category,'其他');
assert.throws(()=>L.purchase(draft,{date:'2026-09-20',amount:'65',items:[{name:'   '}]},'2026-09-27'));
const differentName={...bought,items:[{...base.items[0],name:'洗衣液'}]};
assert.equal(L.summary([base,differentName]).groups.length,2,'old category does not merge different names');
assert.equal(L.duplicates(differentName,[base],'2026-09-25').length,0,'same old category is not a duplicate name');
assert.equal(L.summary([{...base,items:[base.items[0],{...base.items[0],name:' 牙膏A '}]}]).groups[0].purchases,1);
console.log('Name-only product recording checks passed');
